package ru.dankoy.leetcode.array_string;

import java.util.Arrays;

/**
 * 389. Find the Difference
 * Solved
 * Easy
 * 
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 * 
 * 
 * 
 * Example 1:
 * 
 * Input: s = "abcd", t = "abcde"
 * Output: "e"
 * Explanation: 'e' is the letter that was added.
 * 
 * Example 2:
 * 
 * Input: s = "", t = "y"
 * Output: "y"
 * 
 * 
 * 
 * Constraints:
 * 
 * 0 <= s.length <= 1000
 * t.length == s.length + 1
 * s and t consist of lowercase English letters.
 * 
 * 
 */
public class FindTheDifference {

    public static void main(String[] args) {

        String s = "abcd";
        String t = "abcde";

        findTheDifference(s, t);

    }

    public static char findTheDifference(String s, String t) {

        char[] sChars = s.toCharArray();
        Arrays.sort(sChars);

        char[] tChars = t.toCharArray();
        Arrays.sort(tChars);

        int i = 0;

        while (i < tChars.length) {

            if (i == sChars.length) {
                return tChars[i];
            }

            char sC = sChars[i];
            char tC = tChars[i];

            if (sC != tC) {
                return tC;
            } else {
                i++;
            }

        }

        return tChars[tChars.length];

    }

}
